version: '3.8'

services:
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: order_db
    ports:
      - "3309:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql

volumes:
  mysql-order-data: